# Generated by Django 4.2 on 2024-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Vendor', 'Vendor'), ('Customer', 'Customer')], default=None, max_length=255, null=True),
        ),
    ]
